#!/usr/bin/env python3

import argparse
import datetime
import os
import subprocess
import sys
import time

MIRROR_DIR = None # change this

# command line args
parser = argparse.ArgumentParser()
parser.add_argument("--daily", action="store_true")
args = parser.parse_args()

# read repo list
with open('repos', 'r') as f:
    urls = [line.strip() for line in f if line.strip()]

# check valid mirror directory
if MIRROR_DIR is None:
    print("mirror directory is not set, exiting.")
    sys.exit(1)
os.makedirs(MIRROR_DIR, exist_ok=True)
os.chdir(MIRROR_DIR)

def clone():
    print(datetime.datetime.now())

    for url in urls:
        url = url.rstrip('/') # remove trailing /
        repo = url.split('/')[-1] # repo name
        repo = repo + ".git" # add .git to match bare repo

        if os.path.isdir(repo): # repo exists, update
            print("updating " + repo)
            subprocess.run(["git", "-C", repo, "fetch", "--all", "--prune", "--prune-tags"])
        else:
            subprocess.run(["git", "clone", "--mirror", url])

if args.daily:
    while True:
        clone()
        time.sleep(24 * 60 * 60)
else:
    clone()
